# Generated by Django 4.0.4 on 2022-08-16 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='content',
        ),
    ]
