# Generated by Django 4.0.4 on 2022-08-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_remove_movie_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
